#!/bin/bash
export BAKERY_NAMESPACE=<YOUR NAMESPACE HERE>
export BAKERY_IMAGE="pangeo/pangeo-forge-bakery-images:pangeonotebook-2021.06.05_prefect-0.14.22_pangeoforgerecipes-0.4.0"
export PREFECT__CLOUD__AGENT__AUTH_TOKEN=<YOUR TOKEN HERE>
export PREFECT__CLOUD__AUTH_TOKEN=<YOUR TOKEN HERE>
export PREFECT_PROJECT=<PROJECT NAME HERE>
export PREFECT__CLOUD__AGENT__LABELS="{}"
export STORAGE_SERVICE_ACCOUNT_NAME=<ACCOUNT 1 HERE>
export CLUSTER_SERVICE_ACCOUNT_NAME=<ACCOUNT 2 HERE>
